#++++++++++++++++++++++++++++++++++++++
# Debian 8 PHP-Nginx Docker container
#++++++++++++++++++++++++++++++++++++++

FROM pocscan/run:2.1
MAINTAINER kbz 

# Copy requirements.txt 
RUN pip install bs4
RUN apt-get install nmap -y
