#++++++++++++++++++++++++++++++++++++++
# Debian 8 PHP-Nginx Docker container
#++++++++++++++++++++++++++++++++++++++

FROM ubuntu/env:1.0 
MAINTAINER kbz 

COPY superenv.conf /etc/supervisor/conf.d/superenv.conf
COPY nginx_uwsgi /etc/nginx/sites-enabled/nginx_uwsgi 

COPY supervisord.conf /etc/supervisor/supervisord.conf

COPY greenlet.py /usr/local/lib/python2.7/dist-packages/gevent/greenlet.py

EXPOSE 8000

ENTRYPOINT ["/etc/init.d/supervisor","start"]
